import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/mainHeader/MainHeader";
import Footer from "@/components/footer/Footer";
import { Suspense } from "react";
import StoreProvider from "@/components/cart/store/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <MainHeader />
          <Suspense fallback="Loading...">{children}</Suspense>
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
