import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/mainHeader/MainHeader";
import Footer from "@/components/footer/Footer";
import { Suspense } from "react";
import StoreProvider from "@/components/cart/store/StoreProvider";
import Loader from "@/components/loader/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Uzum Market - O'zbekistondagi internet-do'kon",
  description: "Generated by Uzum market",
  content: 'width=device-width, initial-scale=1, user-scalable=no'
  
};

import dynamic from 'next/dynamic'

const Scroller = dynamic(
  () => import("./Scroller"),
  { ssr: false }
)


export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="uz">
        <body className={inter.className}>
          <MainHeader />
          <Suspense fallback={<Loader />}>{children}</Suspense>
          <Footer />
          <Scroller />
        </body>
      </html>
    </StoreProvider>
  );
}
